module.exports = {
    MONGODB_URI: process.env.MONGODB_URI, //MONGO DB URL
    SESSION_SECRET: process.env.SESSION_SECRET, //SECRET KEY SESSION
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,// SENDGRID API KEY
    EMAIL_FROM: process.env.EMAIL_FROM, //FROM EMAIL
    BASE_URL: process.env.BASE_URL //BASE URL
}